use strict;
use Data::Dumper;

# Each new term in the Fibonacci sequence is generated by adding the previous 
# two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.


my $term_one = 1;
my $term_two = 1;
my $new_term;
my @list_term;

for (1 ... 3999999) {

 #for ( 1 ... 10) { 
     if ( $term_one >= 1) {
       $new_term = $term_one + $term_two;
       $term_two = $term_one;
       $term_one = $new_term;
        
        if ( ($new_term/2  ) !~ /\D/ ) {
            push( @list_term , $new_term );
        }
         
      } 

}

print Dumper(\@list_term);
print eval ( join ( '+' , @list_term) ) ;
